version: '3'

services:
  get_service:
    image: nwilliam/cloud-computing:ex3.0-get
    container_name: get_service
    ports:
      - "3031:3031"

  post_service:
    image: nwilliam/cloud-computing:ex3.0-post
    container_name: post_service
    ports:
      - "3032:3032"

  put_service:
    image: nwilliam/cloud-computing:ex3.0-put
    container_name: put_service
    ports:
      - "3033:3033"

  delete_service:
    image: nwilliam/cloud-computing:ex3.0-delete
    container_name: delete_service
    ports:
      - "3034:3034"

  frontend_service:
    image: nwilliam/cloud-computing:ex3.0-ui
    container_name: frontend_service
    ports:
      - "3030:3030"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - get_service
      - post_service
      - put_service
      - delete_service
      - frontend_service
